### ISSUE TITLE
do not use stringify => true when using equatable

### ISSUE THREAD

**Issue by subzero911** [bxqm/dart_data_class_generator#64]
`generate toString()` creates perfectly fine method. But when we use equatable, on `generate toString()` command your extension now generates not a full `toString()` body but `stringify => true`
But `stringify` produces ugly output like `Person(1, John, true, false, 4, false, true)`
(see this issue https://github.com/felangel/equatable/issues/92, it's impossible to create named fields without code generation, so the proposed solution is to create full toString() method).
Consdiering the above, please leave toString() unchanged.

**Comment by bxqm** [comment]
Will do in the next update. Meanwhile, you could remove the `extends Equatable`, generate `toString` method and then paste the `extends Equatable` back again.
