### ISSUE TITLE
Failing with 'class must have at least 1 property'

### ISSUE THREAD

**Issue by BillKeenan** [bxqm/dart_data_class_generator#76]
Trying on a test class, I believe this should work

``````
class test {
    final String one
}
``````

All that happens is it prepends 
``````
import 'dart:convert';
``````

And shows this error:
``````
test couldn't be converted to a data class: Class must have at least one property!
``````

**Comment by BillKeenan** [comment]
also of note, the quick fix menu doesn't come up at all, I'm executing this via the command pallet
Mac OS, vscode

**Comment by bxqm** [comment]
~~~dart
class Test {
    final String one;
}
~~~

You're missing the semicolon. Also dart classes are usually named using upper camelcase.

**Comment by BillKeenan** [comment]
well, that shows me. thanks.
