### ISSUE TITLE
Handle Enums with Enum.name and Enum.value.byName() introduced with dart 2.15

### ISSUE THREAD

**Issue by mklepaczko** [bxqm/dart_data_class_generator#79]
Since handling enums to and from String was introduced with dart 2.15 it would be nice to have the generator handle enums. Now it considers them as regular classes and applies toMap() and fromMap() functions.

https://github.com/dart-lang/language/issues/158

**Comment by cedvdb** [comment]
Also maps containing an enum as the key ! This is as important because it's the other place beside a direct property where the enum could be used.
